"""Initial migration

Revision ID: 562b35804942
Revises: 
Create Date: 2024-11-25 21:33:00.635460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562b35804942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_points')
    # ### end Alembic commands ###
